#!/bin/bash
# deploy.sh — Full first-time deployment on Ubuntu 22.04
# Usage: bash deploy.sh yourdomain.com your@email.com
set -euo pipefail

DOMAIN="${1:?Usage: bash deploy.sh <domain> <email>}"
EMAIL="${2:?Usage: bash deploy.sh <domain> <email>}"
APP_DIR="/opt/greenfield-farm-care"

echo "==> [1/8] Installing system packages"
apt-get update -q
apt-get install -yq docker.io docker-compose-plugin git curl ufw

echo "==> [2/8] Configuring firewall"
ufw --force enable
ufw allow OpenSSH
ufw allow 80/tcp
ufw allow 443/tcp

echo "==> [3/8] Cloning / updating repository"
if [ -d "$APP_DIR/.git" ]; then
  git -C "$APP_DIR" pull
else
  git clone https://github.com/YOUR_ORG/greenfield-farm-care.git "$APP_DIR"
fi
cd "$APP_DIR"

echo "==> [4/8] Creating env files"
if [ ! -f .env ]; then
  cp .env.example .env
  echo "  !! Fill in .env then re-run this script."
  exit 1
fi
if [ ! -f backend/.env.production ]; then
  cp backend/.env.production.example backend/.env.production
  echo "  !! Fill in backend/.env.production then re-run this script."
  exit 1
fi

# Replace placeholder domain in nginx configs
sed -i "s/yourdomain.com/$DOMAIN/g" nginx/conf.d/app.conf
sed -i "s/yourdomain.com/$DOMAIN/g" nginx/conf.d/app-init.conf
sed -i "s/VITE_API_URL=.*/VITE_API_URL=https:\/\/$DOMAIN/" .env

echo "==> [5/8] Building images"
docker compose build --no-cache

echo "==> [6/8] Starting services (HTTP-only first, for SSL challenge)"
cp nginx/conf.d/app-init.conf nginx/conf.d/active.conf
rm -f nginx/conf.d/app.conf
docker compose up -d db backend frontend nginx

echo "  Waiting 10 s for services to be ready..."
sleep 10

echo "==> [7/8] Obtaining Let's Encrypt SSL certificate"
docker compose run --rm certbot certonly \
  --webroot -w /var/www/certbot \
  --email "$EMAIL" \
  --agree-tos --no-eff-email \
  -d "$DOMAIN" -d "www.$DOMAIN"

echo "==> [8/8] Switching to HTTPS nginx config and reloading"
cp nginx/conf.d/active.conf nginx/conf.d/app-init.conf
cp /dev/stdin nginx/conf.d/active.conf < /dev/null

# Restore the SSL-enabled config (we renamed it earlier)
cat > nginx/conf.d/active.conf << 'NGINXEOF'
# This file is generated by deploy.sh — edit nginx/conf.d/app.conf instead.
NGINXEOF
cp nginx/conf.d/app.conf nginx/conf.d/active.conf 2>/dev/null || \
  cp "$APP_DIR/nginx/conf.d/app.conf" nginx/conf.d/active.conf

docker compose exec nginx nginx -s reload

echo ""
echo "✅  Deployment complete!"
echo "   https://$DOMAIN"
echo ""
echo "   Admin login:  admin@greenfield.com / Admin@123"
echo "   Run seed:     docker compose exec backend python seed.py"
